/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.GenerateWindowTransporter;
import conectors.KeyPairCreation;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bekcic
 */
public class GenerateKeyPairWindow extends javax.swing.JFrame {

    JFrame parent;
    GenerateWindowTransporter transp;

    /**
     * Creates new form Generate
     */
    public GenerateKeyPairWindow(JFrame parent) {
        super("Generate Key Pair");
        initComponents();
        transp = new GenerateWindowTransporter();
        this.parent = parent;
        this.setVisible(true);

        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keyVal = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vaziOd = new javax.swing.JTextField();
        VaziDo = new javax.swing.JTextField();
        SerijskiBroj = new javax.swing.JLabel();
        serialNum = new javax.swing.JTextField();
        VelicinaKljuca = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        val512 = new javax.swing.JRadioButton();
        val1024 = new javax.swing.JRadioButton();
        val2048 = new javax.swing.JRadioButton();
        val4096 = new javax.swing.JRadioButton();
        verzija1 = new javax.swing.JRadioButton();
        verzija2 = new javax.swing.JRadioButton();
        verzija3 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CN = new javax.swing.JTextField();
        OU = new javax.swing.JTextField();
        O = new javax.swing.JTextField();
        L = new javax.swing.JTextField();
        ST = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        E = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        generisi = new javax.swing.JButton();
        nazad = new javax.swing.JButton();
        ekstenzije = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        keyPairAlias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Osnovne informacije");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Vazi od");

        jLabel3.setText("Vazi do");

        SerijskiBroj.setText("Serijski broj");

        jLabel4.setText("Veličina ključeva:");

        keyVal.add(val512);
        val512.setSelected(true);
        val512.setText("512");

        keyVal.add(val1024);
        val1024.setText("1024");

        keyVal.add(val2048);
        val2048.setText("2048");

        keyVal.add(val4096);
        val4096.setText("4096");

        verzija1.setText("Verzija 1");
        verzija1.setEnabled(false);
        verzija1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verzija1ActionPerformed(evt);
            }
        });

        verzija2.setText("Verzija 2");
        verzija2.setEnabled(false);
        verzija2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verzija2ActionPerformed(evt);
            }
        });

        verzija3.setSelected(true);
        verzija3.setText("Verzija 3");
        verzija3.setEnabled(false);
        verzija3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verzija3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VelicinaKljucaLayout = new javax.swing.GroupLayout(VelicinaKljuca);
        VelicinaKljuca.setLayout(VelicinaKljucaLayout);
        VelicinaKljucaLayout.setHorizontalGroup(
            VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VelicinaKljucaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VelicinaKljucaLayout.createSequentialGroup()
                        .addGroup(VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(val4096))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VelicinaKljucaLayout.createSequentialGroup()
                        .addGroup(VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VelicinaKljucaLayout.createSequentialGroup()
                                .addComponent(val2048)
                                .addGap(62, 62, 62)
                                .addComponent(verzija3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(VelicinaKljucaLayout.createSequentialGroup()
                                .addComponent(val1024)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verzija2))
                            .addGroup(VelicinaKljucaLayout.createSequentialGroup()
                                .addComponent(val512)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verzija1)))
                        .addGap(27, 27, 27))))
        );
        VelicinaKljucaLayout.setVerticalGroup(
            VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VelicinaKljucaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(val512)
                    .addComponent(verzija1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(val1024)
                    .addComponent(verzija2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VelicinaKljucaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(val2048)
                    .addComponent(verzija3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(val4096)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SerijskiBroj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(serialNum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vaziOd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VaziDo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(VelicinaKljuca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaziOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(VaziDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SerijskiBroj))
                .addGap(18, 18, 18)
                .addComponent(VelicinaKljuca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Informacije o korisniku");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setText("CN");

        jLabel7.setText("OU");

        jLabel8.setText("O");

        jLabel9.setText("L");

        jLabel10.setText("ST");

        jLabel11.setText("C");

        jLabel12.setText("E");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OU, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(O)
                    .addComponent(L)
                    .addComponent(ST)
                    .addComponent(C)
                    .addComponent(E))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        generisi.setText("Generiši");
        generisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generisiActionPerformed(evt);
            }
        });

        nazad.setText("Nazad");
        nazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazadActionPerformed(evt);
            }
        });

        ekstenzije.setText("Ekstenzije");
        ekstenzije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekstenzijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nazad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ekstenzije, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(generisi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazad)
                    .addComponent(generisi)
                    .addComponent(ekstenzije))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel13.setText("Ime para ključeva");

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keyPairAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keyPairAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekstenzijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekstenzijeActionPerformed
        this.setVisible(false);
        new KeyExtensionsWindow(this, transp);
    }//GEN-LAST:event_ekstenzijeActionPerformed

    private void nazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazadActionPerformed
        this.setVisible(false);
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nazadActionPerformed

    private void verzija2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verzija2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verzija2ActionPerformed

    private void verzija1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verzija1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verzija1ActionPerformed

    private void verzija3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verzija3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verzija3ActionPerformed

    private void generisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generisiActionPerformed

        if (CN.getText().trim().equals("") || OU.getText().trim().equals("") || O.getText().trim().equals("")
                || L.getText().trim().equals("") || ST.getText().trim().equals("")
                || C.getText().trim().equals("") || E.getText().trim().equals("")
                || vaziOd.getText().trim().equals("") || VaziDo.getText().trim().equals("")
                || serialNum.getText().trim().equals("")
                || keyPairAlias.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Niste popunili sva polja!");
            return;
        }

        ///////////////DATUM
        String day, month, year;

//        char[] toParse = vaziOd.getText().trim().toCharArray();
//        try {
//            int i = 0;
//            day = "";
//            while (true) {
//                char c = toParse[i++];
//                if (c == '.') {
//                    break;
//                }
//                day += c;
//            }
//
//            int dayVal = Integer.parseInt(day);
//            if(dayVal<1 || dayVal>31)
//            {
//            JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.mm.yyyy.");
//            return;
//            }
//            
//            i = 0;
//            month = "";
//            while (true) {
//                char c = toParse[i++];
//                if (c == '.') {
//                    break;
//                }
//                month += c;
//            }
//
//            int monVal = Integer.parseInt(day);
//            if(monVal<1 || monVal>12)
//            {
//            JOptionPane.showMessageDialog(this, "Datum mora biti u formatu dd.mm.yyyy.");
//            return;
//            }
//            
//            i = 0;
//            year = "";
//            while (true) {
//                char c = toParse[i++];
//                if (c == '.') {
//                    break;
//                }
//                year += c;
//            }
//
//            int yearVal = Integer.parseInt(day);
//            
//            //moze ovde da bude jos par provera datuma, ali nemam vremena
//            
//            Date validFrom = new Date();
//            validFrom.setDay
//            
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Datum mora da bude broj!");
//            return;
//        }
        Date validFrom;
        DateFormat dateFormat = new SimpleDateFormat("dd.mm.yyyy.", Locale.ENGLISH);
        try {
            validFrom = dateFormat.parse(vaziOd.getText().trim());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum mora da bude u formatu dd.mm.yyyy.");
            return;
        }

        Date validTo;
        try {
            validTo = dateFormat.parse(VaziDo.getText().trim());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum mora da bude u formatu dd.mm.yyyy.");
            return;
        }

        if (validTo.before(validFrom)) {
            JOptionPane.showMessageDialog(this, "Datum kada pocinje da vazi "
                    + "sertifikat mora da bude pre datuma kada on prestaje da vazi!");
            return;
        }

        transp.setValidFrom(validFrom);
        transp.setValidTo(validTo);

        ///////////////user name
        transp.setUserC(C.getText().trim());
        transp.setUserCN(CN.getText().trim());
        transp.setUserE(E.getText().trim());
        transp.setUserL(L.getText().trim());
        transp.setUserO(O.getText().trim());
        transp.setUserOU(OU.getText().trim());
        transp.setUserST(ST.getText().trim());

        ///////serijski broj
        try {
            Integer.parseInt(serialNum.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Serijski broj mora da bude pozitivan ceo broj!");
            return;
        }

        transp.setSerialNum(serialNum.getText().trim());

        //////velicina kljuca
        if (val512.isSelected()) {
            transp.setKeySize("512");
        } else if (val1024.isSelected()) {
            transp.setKeySize("1024");
        } else if (val2048.isSelected()) {
            transp.setKeySize("2048");
        } else {
            transp.setKeySize("4096");
        }
         transp.setVersion(3);
         transp.setKeyPairName(keyPairAlias.getText().trim());

        try {
            if (!KeyPairCreation.createKeyPair(transp)) {
                JOptionPane.showMessageDialog(this, "Doslo je do greske!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske!");
        }
        
        this.setVisible(false);
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C;
    private javax.swing.JTextField CN;
    private javax.swing.JTextField E;
    private javax.swing.JTextField L;
    private javax.swing.JTextField O;
    private javax.swing.JTextField OU;
    private javax.swing.JTextField ST;
    private javax.swing.JLabel SerijskiBroj;
    private javax.swing.JTextField VaziDo;
    private javax.swing.JPanel VelicinaKljuca;
    private javax.swing.JButton ekstenzije;
    private javax.swing.JButton generisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField keyPairAlias;
    private javax.swing.ButtonGroup keyVal;
    private javax.swing.JPanel namePanel;
    private javax.swing.JButton nazad;
    private javax.swing.JTextField serialNum;
    private javax.swing.JRadioButton val1024;
    private javax.swing.JRadioButton val2048;
    private javax.swing.JRadioButton val4096;
    private javax.swing.JRadioButton val512;
    private javax.swing.JTextField vaziOd;
    private javax.swing.JRadioButton verzija1;
    private javax.swing.JRadioButton verzija2;
    private javax.swing.JRadioButton verzija3;
    // End of variables declaration//GEN-END:variables
}
