/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Bekcic
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public MainWindow() {
        super("Main Window");
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generisanje = new javax.swing.JButton();
        izvozuvoz = new javax.swing.JButton();
        Detalji = new javax.swing.JButton();
        Potpisivanje = new javax.swing.JButton();
        izvoz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generisanje.setText("Generisanje novog para ključeva");
        generisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generisanjeActionPerformed(evt);
            }
        });

        izvozuvoz.setText("Izvoz/Uvoz postojećeg para ključeva");
        izvozuvoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvozuvozActionPerformed(evt);
            }
        });

        Detalji.setText("Pregled detalja postojećeg para ključeva");
        Detalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetaljiActionPerformed(evt);
            }
        });

        Potpisivanje.setText("Potpisivanje");
        Potpisivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotpisivanjeActionPerformed(evt);
            }
        });

        izvoz.setText("Izvoz");
        izvoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvozActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(izvoz, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Potpisivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Detalji, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izvozuvoz, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(generisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izvozuvoz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Detalji, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Potpisivanje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izvoz, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izvozuvozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvozuvozActionPerformed
        this.setVisible(false);
        this.setResizable(false);
        new ImportExportWindow(this);
    }//GEN-LAST:event_izvozuvozActionPerformed

    private void generisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generisanjeActionPerformed
        this.setVisible(false);
        this.setResizable(false);
        new GenerateKeyPairWindow(this);
    }//GEN-LAST:event_generisanjeActionPerformed

    private void DetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetaljiActionPerformed
        this.setVisible(false);
        new ViewKeyPairDetails(this);
    }//GEN-LAST:event_DetaljiActionPerformed

    private void izvozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvozActionPerformed
        this.setVisible(false);
        new CertExportWindow(this);
    }//GEN-LAST:event_izvozActionPerformed

    private void PotpisivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotpisivanjeActionPerformed
       this.setVisible(false);
       new KeyPairSigninWindow(this);
    }//GEN-LAST:event_PotpisivanjeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Detalji;
    private javax.swing.JButton Potpisivanje;
    private javax.swing.JButton generisanje;
    private javax.swing.JButton izvoz;
    private javax.swing.JButton izvozuvoz;
    // End of variables declaration//GEN-END:variables
}
